# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommendations.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15recommendations.proto\"^\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x1f\n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\r.BookCategory\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05\"/\n\x12\x42ookRecommendation\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\"F\n\x16RecommendationResponse\x12,\n\x0frecommendations\x18\x01 \x03(\x0b\x32\x13.BookRecommendation*?\n\x0c\x42ookCategory\x12\x0b\n\x07MYSTERY\x10\x00\x12\x13\n\x0fSCIENCE_FICTION\x10\x01\x12\r\n\tSELF_HELP\x10\x02\x32O\n\x0fRecommendations\x12<\n\tRecommend\x12\x16.RecommendationRequest\x1a\x17.RecommendationResponseb\x06proto3')

_BOOKCATEGORY = DESCRIPTOR.enum_types_by_name['BookCategory']
BookCategory = enum_type_wrapper.EnumTypeWrapper(_BOOKCATEGORY)
MYSTERY = 0
SCIENCE_FICTION = 1
SELF_HELP = 2

_RECOMMENDATIONREQUEST = DESCRIPTOR.message_types_by_name['RecommendationRequest']
_BOOKRECOMMENDATION = DESCRIPTOR.message_types_by_name['BookRecommendation']
_RECOMMENDATIONRESPONSE = DESCRIPTOR.message_types_by_name['RecommendationResponse']
RecommendationRequest = _reflection.GeneratedProtocolMessageType('RecommendationRequest', (_message.Message,), {
    'DESCRIPTOR': _RECOMMENDATIONREQUEST,
    '__module__': 'recommendations_pb2'
    # @@protoc_insertion_point(class_scope:RecommendationRequest)
})
_sym_db.RegisterMessage(RecommendationRequest)

BookRecommendation = _reflection.GeneratedProtocolMessageType('BookRecommendation', (_message.Message,), {
    'DESCRIPTOR': _BOOKRECOMMENDATION,
    '__module__': 'recommendations_pb2'
    # @@protoc_insertion_point(class_scope:BookRecommendation)
})
_sym_db.RegisterMessage(BookRecommendation)

RecommendationResponse = _reflection.GeneratedProtocolMessageType('RecommendationResponse', (_message.Message,), {
    'DESCRIPTOR': _RECOMMENDATIONRESPONSE,
    '__module__': 'recommendations_pb2'
    # @@protoc_insertion_point(class_scope:RecommendationResponse)
})
_sym_db.RegisterMessage(RecommendationResponse)

_RECOMMENDATIONS = DESCRIPTOR.services_by_name['Recommendations']
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _BOOKCATEGORY._serialized_start = 242
    _BOOKCATEGORY._serialized_end = 305
    _RECOMMENDATIONREQUEST._serialized_start = 25
    _RECOMMENDATIONREQUEST._serialized_end = 119
    _BOOKRECOMMENDATION._serialized_start = 121
    _BOOKRECOMMENDATION._serialized_end = 168
    _RECOMMENDATIONRESPONSE._serialized_start = 170
    _RECOMMENDATIONRESPONSE._serialized_end = 240
    _RECOMMENDATIONS._serialized_start = 307
    _RECOMMENDATIONS._serialized_end = 386
# @@protoc_insertion_point(module_scope)
